[#46] feat: implement pet list and pet info screen
2022-2-Graduation-Project/BowwowCare-FE pull request #47
Opened 2023-01-31 09:16 UTC by suzinxix

2023-01-31 09:31 UTC, 0hee0 requested changes
변수명 빼고 아주 굳굳!
변수명은 변경 요청드립니다 ㅎ__ㅎ

2023-01-31 09:31 UTC, 0hee0 commented on bowwowcare/src/utils/Calculator.js
> +export const getBwDate = (date) => {
변수명 변경해주세용용
`getDurationDate` 추천추천!

2023-01-31 09:31 UTC, 0hee0 commented on bowwowcare/src/utils/Calculator.js
> +    const stDate = new Date(date.getFullYear(), date.getMonth() + 1, date.getDate());
`st` `bt` 다 잘 이해가 안가요 ^q^

2023-01-31 09:31 UTC, 0hee0 commented on bowwowcare/src/views/HomePage/PetList/PetList.js
> +import PetInfo from './PetInfo/PetInfo'
`./Sections/PetInfo` 추천 추천

2023-01-31 09:31 UTC, 0hee0 commented on bowwowcare/src/views/HomePage/PetList/PetList.js
> +      { props.pet.map((a, i)=>{
`map` 적용할 `pet`은 `pets`로, `a`는 `pet`으로 변경하면 좋을 것 같습니다!

2023-01-31 13:59 UTC, suzinxix commented on bowwowcare/src/utils/Calculator.js
> +export const getBwDate = (date) => {
추천 감사합니당당

2023-01-31 14:01 UTC, suzinxix commented on bowwowcare/src/views/HomePage/PetList/PetList.js
> +import PetInfo from './PetInfo/PetInfo'
오오오...!!

2023-01-31 14:02 UTC, suzinxix commented on bowwowcare/src/views/HomePage/PetList/PetList.js
> +      { props.pet.map((a, i)=>{
앞으로 참고하겠습니다 ^!^

2023-01-31 14:03 UTC, suzinxix commented on bowwowcare/src/utils/Calculator.js
> +    const stDate = new Date(date.getFullYear(), date.getMonth() + 1, date.getDate());
앞으로 변수명 고민을 더 신중히 하겠습니다 ....

2023-02-10 04:38 UTC, 0hee0 approved these changes
반영 감사하옵니다 🙇🏻‍♀️

2023-02-10 04:38 UTC, merged